[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Daniel Pape <daniel@d-pape.info>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"
nom = "6.0.1"
petgraph = "0.5.1"
rayon = "1.5.0"